name: CI

on:
  pull_request:
  push:
      branches:
      - master

env:
  MIX_ENV: test

jobs:
  test:
    name: mix test (Erlang/OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})
    runs-on: ubuntu-latest
    container: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.13.1
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.9.0
            otp: 21.0.1
          - elixir: 1.9.3
            otp: 22.3.4.9
          - elixir: 1.10.0
            otp: 21.0.1
          - elixir: 1.10.4
            otp: 23.2.3
          - elixir: 1.11.0
            otp: "21.0"
          - elixir: 1.11.2
            otp: 23.2.4
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix test

  code_check:
    name: Check formatted
    runs-on: ubuntu-latest
    container: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.13.1
    strategy:
      matrix:
        include:
          - elixir: 1.11.2
            otp: 23.2.4
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Check formatted
        run: mix format --check-formatted

      - name: Check quality
        run: mix credo